/** User-facing English strings. Keep UI copy here for later i18n. */
export const strings = {
  appTitle: "Harbor",
  emptyShellHeading: "Harbor",
  emptyShellBody: "Your mail will show up here.",
  statusLoading: "Starting…",
  statusReady: "Ready",
  addAccount: "Add account",
  addGmail: "Add Gmail",
  addOutlook: "Add Outlook",
  signingIn: "Waiting for browser sign-in…",
  noAccounts: "No accounts yet",
  selectAccount: "Select an account",
  accounts: "Accounts",
  inbox: "Inbox",
  folders: "Folders",
  syncFolders: "Sync folders",
  syncingFolders: "Syncing folders…",
  noFolders: "No folders yet — sync to load mailboxes.",
  noMessages: "No messages in this folder.",
  selectFolder: "Select a folder",
  syncingMessages: "Syncing…",
  messages: "messages",
  loadingMessage: "Loading message…",
  loadImages: "Load images",
  imagesBlocked: "Remote images are blocked.",
  from: "From",
  to: "To",
  date: "Date",
  statusOnline: "Connected",
  statusOffline: "Offline — showing cached mail",
  statusReconnecting: "Reconnecting…",
  markRead: "Mark read",
  markUnread: "Mark unread",
  star: "Star",
  unstar: "Unstar",
  archive: "Archive",
  delete: "Delete",
  move: "Move",
  undo: "Undo",
  viewConversation: "Conversations",
  viewFlat: "Flat",
  search: "Search",
  searchPlaceholder: "Search mail…",
  searchNoResults: "No matches.",
  searchEmpty: "Type to search synced mail.",
  gmailOauthNotConfigured:
    "Gmail OAuth is not configured. Set HARBOR_GMAIL_CLIENT_ID or add oauth.json in the data directory.",
  outlookOauthNotConfigured:
    "Outlook OAuth is not configured. Set HARBOR_OUTLOOK_CLIENT_ID or add oauth.json in the data directory.",
} as const;
